name: Check
on: push

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-python@v2
              with:
                  python-version: "3.8"

            - uses: pre-commit/action@v2.0.3

            - name: Test
              run: |
                  pip install -r requirements-dev.txt
                  PYTHONPATH=src pytest
